version: "3"
services:
  trip_advisor_postgres_db:
    image: postgres:latest
    container_name: PostgresCont
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres123
    ports:
      - "5434:5432"
    volumes:
      - postgres_db:/var/lib/postgresql/data
volumes:
  postgres_db:
    driver: local
