version: "3"
services:
  trip_advisor_postgres_db:
    image: postgres:latest
    container_name: PostgresCont
    restart: always
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_db:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  postgres_db: # Define the named volume here
    driver: local
